ae_comm: 0
cnn_input_proc: 0
coord_mask_type: optout
delayed_comm: 0
hi: 128
hc: 64
hm: 32
hs: 1
# train
batch_size: 512
lambda_q: 10 # 10,20,20
min_buffer_len: 5000
max_buffer_len: 10000
chunk_size: 1
update_target_interval: 40000  # 20k,30k,40k
K_epochs: 0.02
coord_K_epochs: 0.02