ae_comm: 0
cnn_input_proc: 0
coord_mask_type: "optout"
delayed_comm: 0
hi: 256
hc: 256
hm: 16
hs: 1
norm_layer: 1
# train
batch_size: 16
lambda_q: 10
min_buffer_len: 5000
max_buffer_len: 20000
chunk_size: 10  # 1
update_target_interval: 100
K_epochs: 0.02
coord_K_epochs: 0.02

